### ISSUE TITLE
Component Breaks in 0.96b0

### ISSUE THREAD

**Issue by statuskwolek** [MizterB/homeassistant-infinitude#14]
Accidentally updated last night — still receive the message about the custom component loading, but I no longer have an entity under climate and UI elements come back as unknown.

Will up my log level and try to add to this shortly.

**Comment by statuskwolek** [comment]
Thu Jul 11 2019 06:19:45 GMT-0400 (EDT)

Platform not found: climate.infinitude

**Comment by MizterB** [comment]
There are wholesale changes to climate coming in .96, which may be breaking things.  I haven't assessed the impact yet - my recommendation for now would be to downgrade if you can.

**Comment by MizterB** [comment]
For anyone following this....a pretty substantial rewrite is in progress.  The new 'preset' feature fundamentally changes the way I think about the hold behavior and activity settings, so I'm working through it.  I can't personally upgrade HA until I get this fixed, so it is a priority!

**Comment by MizterB** [comment]
Fixed in latest release

**Comment by aicarmic** [comment]
Rockstar! Thanks for maintaining this component for us @MizterB, let me know how I can support/buy you a beer 🍺
