### ISSUE TITLE
Removal of Zone Name causes entity names swap if two instances of component are used

### ISSUE THREAD

**Issue by Tangston311** [MizterB/homeassistant-infinitude#16]
I have two, separate, Bryant HVAC systems (each with it’s own thermostat, each with it's own instance of Infinitude running). Before the re-write of this component I got them working by simply having two instance of this component running simultaneously, and using the custom zone name feature to differentiate the two in HA (as both systems are running on their own independent Zone 1).

Now that the zone naming has been deprecated they both come in as “climate_zone_1” and “climate_zone_1_2”, respectively. The issue is that whenever I restart my HA server they’ll switch entity names depending on which one HA sees first, which wreaks havoc on my automations.  So, one time "climate_zone_1" will be my upstairs thermostat and "climate_zone_1_2" will be my main-level thermostat, but if I restart HA they'll spontaneously switch.

**Comment by MizterB** [comment]
The updated zone naming logic in release 0.7 will allow you to override the zone names in either instance to your liking.
