### ISSUE TITLE
KeyError: 'zones'

### ISSUE THREAD

**Issue by carrollj87** [MizterB/homeassistant-infinitude#18]
I am attempting to move to infinitude in Hass.io, and am receiving the following error when starting up Hass.io. 
```
Error while setting up infinitude platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 78, in setup_platform
    zones = status["zones"][0]["zone"]
KeyError: 'zones'
```
I am running Infinitude in docker, and have tried a few instances running on different hosts, and get the same error. The output in the API appears to be ok. I only have 1 zone, and the output matches what is in the Infinitude UI. 

I appreciate your help. Please let me know if there is any additional information I can provide.

**Comment by MizterB** [comment]
Looks like you aren't getting the expected response (or likely any response at all) from Infinitude when this component starts up inside Hassio.  Perhaps this is a name resolution issue?  Maybe try using your Infinitude host's IP address instead of name, and double check the port.
