### ISSUE TITLE
Ability to provide a name to system

### ISSUE THREAD

**Issue by bdf0506** [MizterB/homeassistant-infinitude#2]
I don't see anywhere in the code where you can assign a name to the system. In my non-zoned system, it simply gets a name of `climate.zone_1` instead of a friendly name. You can always customize this name within HA, but perhaps a "name" parameter should be added. This could get tricky with multiple zones though.

**Comment by MizterB** [comment]
Have you looked into the menu options on there thermostat?  Mine has the ability to set zone names, although I'm not sure if is shown if only 1 zone is enabled.  

Current behavior is to use the thermostat's zone name values.  I could set up the component to allow customization of the entity_id and name via the HA device registry - but I need to identify a unique_id value for the thermostat.  Being a custom component, I could reasonably hack in any value I want, but I'd prefer it to be legit.  If I had access to the thermostat serial # or similar, that would be ideal, but I can't find a unique can in the system or status files.  If you can come up with an appropriate value, that would be great.

**Comment by bdf0506** [comment]
On my thermostat, there are no zones, so there is no way to set a name with the thermostat. The only place I see it called anything is when it is called ZONE 1 on the infinitude API which is where you are pulling it from. Infinitude actually also shows me other zones, but none that matter on my system, and none that can be configured. It makes sense that on multi zone units that you’d be pulling the correct name since it’s use configurable. Right now I have placed a customization in customize.yaml which is to apply a friendly_name to climate.zone_1.

**Comment by bdf0506** [comment]
So i did a small hack and set the zone name via the infinitude API, since I don't have the ability to set the zone name in my thermostat. Now it pulls in the name of zone 1, which I've now called "Thermostat", properly into HA. Not sure if that's how we want this to be for non zoned systems with this component, but what I did below does work, and prevents an override needed once the entity gets into HA.

You can set it with this command:
`http://<ip address>:8080/api/config/zones/zone/0/?name=Thermostat`

I don't see a way in the API to pull in the unique thermostat serial number, but if you look within the structure of the files of infinitude, you should see the unique thermostat serial number located within the "states" folder. Many of the .dat files have my serial name as prefixes to these files. You'll also seee the same serial number within the log files of infinitude. Not sure if this can be used that easily since it isn't exposed in the API.

There might be something if you've enabled serial connection for this, since it is getting things like the heat pump  model and s/n, but once again these don't look they are exposed in the api.

**Comment by MizterB** [comment]
I have provided the ability to set a custom zone name via config in the latest release.
