### ISSUE TITLE
Fails to start: "Error doing job: Future exception was never retrieved"

### ISSUE THREAD

**Issue by qwow5** [MizterB/homeassistant-infinitude#25]
Component fails to start with the following error in my logs. I am running Home Assistant 0.114.4.

Error doing job: Future exception was never retrieved

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 122, in setup_platform
    devices.append(InfinitudeZone(infinitude, zones[i]["id"], zone_name))
  File "/config/custom_components/infinitude/climate.py", line 216, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 371, in update
    dt = datetime.datetime(
OverflowError: date value out of range
```

**Comment by qwow5** [comment]
After looking at the Infinitude API and the code in climate.py, the component is not pulling `localTime` from the thermostat correctly. @MizterB Could you take a look at this?

**Comment by qwow5** [comment]
Problem solved: I had to reset the thermostat's built-in schedule to the factory default.

**Comment by tuffcalc** [comment]
> Problem solved: I had to reset the thermostat settings.

@qwow5 I am having the same error(s) as you.  You mention you reset thermostat settings - are you talking on the actual Carrier thermostat?  Trying to solve this.  With thanks.

**Comment by qwow5** [comment]
@tuffcalc Yes. You need to reset the schedule in the installer menu on the thermostat.
To do so, open the menu and press and hold the service menu (hat icon) until it turns green.
Then, go to setup - thermostat - reset factory defaults - select "yes" for "program schedule" and save.

This fixed it for me. Note that it will reset your thermostat's built-in schedule to the factory default. (Was not a problem for me as I set up a schedule in HA instead.)

**Comment by tuffcalc** [comment]
@qwow5 Thank you so much.  That worked and it's now up and running.  Thanks again I really appreciate it!

**Comment by qwow5** [comment]
@tuffcalc You're welcome. Glad I could help!
