### ISSUE TITLE
 InfinityTouch or Infinitude as proxy?

### ISSUE THREAD

**Issue by appleguru** [MizterB/homeassistant-infinitude#27]
At this point would you recommend using InfinityTouch or Infinitude? Is it possible to run either on a system setup with a "stock" HassOS HA image?

**Comment by appleguru** [comment]
Small update: Was able to get Infinitude running on HassOS via docker using this docker image via portainer: https://hub.docker.com/r/scyto/infinitude

(Make sure to set the network to "host" instead of the default "bridge" if you try this)

<img width="1420" alt="Screen Shot 2020-09-19 at 6 32 36 PM" src="https://user-images.githubusercontent.com/595829/93690500-1f4f6200-faa7-11ea-925d-f3467b79efae.png">

**Comment by tylerwmarrs** [comment]
@appleguru I am just now researching this integration myself. Here is a more up to date image. The one you posted was updated 2 months ago.

https://hub.docker.com/r/nebulous/infinitude

**Comment by adamurban** [comment]
That’s the “official” Docker image, which at least currently is x86 only. The one I linked works on arm too/on my rPI. Maybe we can do a PR for a proper cross platform Docker image?

**Comment by scyto** [comment]
Take a look at this one and see if it works, this is test version of official https://hub.docker.com/r/scyto/infinitude
If you need me to update it, let me know.

**Comment by scyto** [comment]
Meant to say, if you need me to update it, let me know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adamurban** [comment]
Yes, yours works perfect (was the one I found/used above).

Any chance you can share your Docker file for that one? Would love to do a PR for the main repo so we can have a cross platform version.

**Comment by tylerwmarrs** [comment]
I understand. I am running home assistant in a virtual machine via Linux on x86_64 hardware. No issues for me.

**Comment by scyto** [comment]
BTW the only change i can see in nebulous git repo since this was made is a change to readme.md  so i don't think mine needs updating.  

The multi-arch build relies on buildx which I only run locally.  docker hub still requires too much scripting than I can be bothered to do do (or know how todo tbh) for automated buildx or multiarc runs :-)  - though there are some new options using build from, github hooks - but i don't have time to investigate that.  You might want to support my open ticket for buildx support in dockerhub.....

Anyhoo the docker file is in my gitrepo.

Is it the dockerfile you need or the buildx syntax or  a fully automated dockerhub multiarch solutions.

The way i normally operate is i wait for someone to ask me to update my multi-arch and the just rerun buildx locally and push - only takes maybe 20 minutes unless the main repo made a breaking change

**Comment by scyto** [comment]
@appleguru did you make that as a stack / service or just as a container?
Also you may want to look at my yaml file in my repo - it already sets the network to host for you :-)
--edit-- ah bollocks, realized i never syned the yaml change, brb

**Comment by scyto** [comment]
@adamurban  can you see if this tag pulls and works on your pi?  i just setup automated buildx multiarch builds!
If it works i can propose to nebulous as this requires minimal work for him

docker pull scyto/infinitude:multi-test

**Comment by adamurban** [comment]
> @adamurban can you see if this tag pulls and works on your pi? i just setup automated buildx multiarch builds!
> If it works i can propose to nebulous as this requires minimal work for him
> 
> docker pull scyto/infinitude:multi-test

Will give it a shot shortly. I just added your image as a new container, set its network to host, and set it to run on startup. Is there a better way?

**Comment by scyto** [comment]
better way, no, just different ways.  For example doing it as stack is for if you have a docker swarm, sounds like you are just doing single node managements rather than swarm.

**Comment by adamurban** [comment]
Yeah, the Home Assistant “stock” RPi image uses Docker under the hood to run everything. So I just added a new container for infinitude so I could run it all on the same pi. Worked flawlessly.

**Comment by adamurban** [comment]
(I guess we’ll see if it persists across updates; hopefully!)

**Comment by scyto** [comment]
@adamurban my mistake it is appleguru that is using portainer, lol, my question was about that :-)

@anyone For any issues with the mutiarch test / or when you have tested please leave feedback here https://github.com/nebulous/infinitude/issues/109 - i am more likely to pay attention to that :-)

**Comment by adamurban** [comment]
(That’s my other account, sorry... it’s always a crapshoot which one I’m logged into apparently)
