### ISSUE TITLE
Lovelace UI not working while on AUTO

### ISSUE THREAD

**Issue by bdf0506** [MizterB/homeassistant-infinitude#3]
When mode is set to auto, lovelace UI seems to struggle. It should show the min and max button on the lovelace UI thermostat, but when in auto seems to only show one dot for temperature. Not sure what lovelace is expecting, maybe the variable name aren't matching what lovelace wants. A workaround is to pull up additional details on the thermostat and you can set the heat/cool temps there.

**Comment by ccalica** [comment]
When editing temps on the detail page, the heat/cool setpoints are reversed.  Changing one causes them to flip and confusion (either thermostat, ha, or infinitude) to result.

**Comment by ccalica** [comment]
I issued a pull request that fixes my problem above.  The thermostat UI appears to be working as well; two dots, can move them, changes are properly affected.  For anyone not wanting to wait, my repo is:

https://github.com/ccalica/homeassistant-infinitude

**Comment by Tangston311** [comment]
@ccalica , thank you for posting this repo!  I was having the same issue and your branch fixed it perfectly.  It's awesome to have my Bryant system finally connected to everything and working properly.  And thanks @MizterB for doing all the initial development!  It's much appreciated.

**Comment by MizterB** [comment]
Changes have been merged.  Thanks!
