### ISSUE TITLE
Controlling Multiple Thermostats in Home Assistant

### ISSUE THREAD

**Issue by brettonw** [MizterB/homeassistant-infinitude#34]
I use Home Assistant to run two thermostats that are controlling two different HVAC systems (don't ask, previous owner installed). When I first set up infinitude, there was an issue running multiple components, so I had to rename the HA custom_component folders (I used "infinitude-1" instead of "infinitude") via a symbolic link to the infinitude repo folder. Later HASS changes required me to make a duplicate of the custom_component folder (infinitude-1, and infinitude-2), because there were code changes required to make sure the "domain" (infinitude-1 or 2) matched the custom_component folder name. In particular, I had to modify the manifest and the climate.py places where "infinitude" was given as the domain name, so my two copies now have "infinitude-1" and "infinitude-2". This appears to be working well right now, but infinitude has been a source of trouble with all these recent HA changes.

a) is it still necessary to run differently named components? Can I just have two components named "infinitude"? 
b) if not, what code changes could be made to make it simper to maintain this type of situation?

**Comment by brettonw** [comment]
@MizterB can you comment on this?

**Comment by richardtallent** [comment]
I'm about to have this same situation -- separate HVACs upstairs and downstairs need to be replaced in my house, and both of the new systems will have a Carrier Infinity Touch Controller (SYSTXCCWIC01-B).

**Comment by jmengit** [comment]
Anybody end up having an "easy" fix or fork that fixes this issue?

**Comment by jmengit** [comment]
For anyone that across this simply duplicating Infinitude in the custom_components folder and renaming the folders did the trick for me. No code modification necessary.

**Comment by brettonw** [comment]
I had a lot of trouble with this in a previous build of HA. The integration registers itself on startup, and two integrations of the same name collide. I haven’t seen any code changes that would fix that, did I miss them?

**Comment by brettonw** [comment]
Did you check the logs, and can you actually control your separate thermostats separately?

**Comment by jmengit** [comment]
You are largely correct. My solution breaks Home Assistant's ability to restart but it does work for that first boot up. Just to clarify heres what I  did: 

1. Install MitzerB's HomeAssistant Infinitude component via HACS
2. Went into HA's file system and duplicated the infinitude folder in custom_components. Named one of these folders Infinitude1 and the other infinitude2
3. Modified configuration.yaml the look for "platform: infinitude1" and "platform: infinitude2"
4. Restarted HA
5. At this point everything works and I can control both thermostats independently
6. HA throws the  "config not valid" "platform error" when attempting to restart 

Sorry for the confusion.

**Comment by jmengit** [comment]
For anyone that comes across this post: FAR from an ideal solution but I've forked this repo and converted everything to be named "Infinitude2". You can add this repo to HACS and everything should work "out of the box". [Fork here](https://github.com/jmengit/homeassistant-infinitude2)

**Comment by MizterB** [comment]
Fixed in https://github.com/MizterB/homeassistant-infinitude-beyond
