### ISSUE TITLE
Stopped working after a few days

### ISSUE THREAD

**Issue by civarson** [MizterB/homeassistant-infinitude#36]
I'm running HA 2021.9.7

Was working fine the  first 48 hours and now I can no longer control the mini split.

> Logger: homeassistant.helpers.entity
> Source: custom_components/midea_ac/climate.py:129
> Integration: midea_ac (documentation)
> First occurred: 9:32:07 AM (1214 occurrences)
> Last logged: 2:35:25 PM
> 
> Update for climate.office_mini_split fails
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
>     raise exc
>   File "/config/custom_components/midea_ac/climate.py", line 129, in async_update
>     await self.hass.async_add_executor_job(self._device.apply)
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 264, in apply
>     self._send_cmd(cmd)
>   File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 208, in _send_cmd
>     responses = self._lan_service.appliance_transparent_send_8370(data)
>   File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 136, in appliance_transparent_send_8370
>     data = self.security.encode_8370(data, msgtype)
>   File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 117, in encode_8370
>     data = self.aes_cbc_encrypt(data, self._tcp_key) + sign
>   File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 57, in aes_cbc_encrypt
>     return AES.new(key, AES.MODE_CBC, iv=self.iv).encrypt(raw)
>   File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
>     return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
>     return modes[mode](factory, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
>     cipher_state = factory._create_base_cipher(kwargs)
>   File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
>     if len(key) not in key_size:
> TypeError: object of type 'NoneType' has no len()
>

**Comment by MizterB** [comment]
This doesn’t appear to have anything to with this integration. The error you posted is for midea_ac.

**Comment by civarson** [comment]
My apologies. This can be deleted.
