### ISSUE TITLE
New attributes, (filter, humid, uv level)

### ISSUE THREAD

**Issue by home409ca** [MizterB/homeassistant-infinitude#42]
Is it possible to add new entity attributes?

I am talking exactly about :
filter_level: 
humid_filter_level: 
uv_filter_level: 

They are available in this add-on:
https://github.com/nfriess/carrier_infinity/issues
The controller transmits this data, so maybe homeassistant-infinitude could be added?

**Comment by bcochrane** [comment]
I think this can issue can be closed now that PR #48 has been merged.

**Comment by sytchi** [comment]
Is there anything more needed for this to become a part of a new version to be available and visible through HACS?

**Comment by MizterB** [comment]
Should have been made available as soon as the PR was merged.

**Comment by sytchi** [comment]
Can we bump the version?

**Comment by MizterB** [comment]
Implemented as sensors in https://github.com/MizterB/homeassistant-infinitude-beyond
