### ISSUE TITLE
Dies when Wifi resets

### ISSUE THREAD

**Issue by macWD** [MizterB/homeassistant-infinitude#45]
Sometimes everything will stop working. No ability to set thermostat, read temperatures, etc. I noticed this would always happen overnight. I reboot HA, and everything works. After some looking through logs, it seemed to happen around 4:00 am. My router was set to reboot daily at 4:00 am. This leads me to believe there is some sort of issue when my router restarts where HA-infinitude loses contact with the infinitude server. Of course the simple workaround is changing the router setting. However, it might be worth looking into.

**Comment by marcteale** [comment]
I don't think the problem is with Infinitude.  I think the SoC that the
thermostat is based on just isn't very good.

My unit won't reconnect to wifi if the WAP switches channels, and nothing
short of a full power cycle will bring it back online.

**Comment by macWD** [comment]
@markteale I don't think it's on the thermostat side. I am able to see everything through the infinitude web interface OK. To be clear, I don't think it's infinitude either. I think it might be homeassistant-infinitude getting confused. Also, it doesn't explain how a HA reboot fixes everything. I think I'll take a look at the code and see if something jumps out at me.

**Comment by macWD** [comment]
> I don't think the problem is with Infinitude.  I think the SoC that the thermostat is based on just isn't very good.
> 
> My unit won't reconnect to wifi if the WAP switches channels, and nothing short of a full power cycle will bring it back online.

Yeah, I think you're right here. I ran 11k pings to the thermostat and got 13% lost packets. They seem to happen in large bursts. Guess I'll have to figure out a workaround in my automation.

**Comment by MizterB** [comment]
Please retry with https://github.com/MizterB/homeassistant-infinitude-beyond
