### ISSUE TITLE
Entity not created and date out of range

### ISSUE THREAD

**Issue by emkayg** [MizterB/homeassistant-infinitude#46]
All of a sudden, the climate entity is no longer available. Has there been a breaking change or somewhere to look to find out why this is happening. Logs only show that this integration is taking too long to load and that there is a date out of range.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/infinitude/climate.py:371
Integration: infinitude (documentation)
First occurred: 10:08:42 AM (1 occurrences)
Last logged: 10:08:42 AM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 122, in setup_platform
    devices.append(InfinitudeZone(infinitude, zones[i]["id"], zone_name))
  File "/config/custom_components/infinitude/climate.py", line 216, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 371, in update
    dt = datetime.datetime(
OverflowError: date value out of range

**Comment by emkayg** [comment]
Turns out this was because schedules were all unpopulated.

**Comment by MizterB** [comment]
Please retry in https://github.com/MizterB/homeassistant-infinitude-beyond
