### ISSUE TITLE
No Streaming Source

### ISSUE THREAD

**Issue by cvanover7** [MizterB/homeassistant-infinitude#47]
The Infinitude proxy is setup and functioning (I can telnet to port 3000 and generate an error in the log) and I've configured the IP and Port (3000) in the Carrier wall control, but I never get any data from the Carrier unit to the proxy, just constant

[2022-12-16 17:57:47.26488] [6] [info] Websocket opened, but no streaming source is available

in the logs. The wall unit is using the latest software version, 4.31.  Any suggestions?

**Comment by cvanover7** [comment]
Sorry, wrong location for this issue.

**Comment by greggitter** [comment]
@cvanover7 for the record, I'm having the same issue, and have been trying for a week to figure it out with no luck over [here](https://github.com/nebulous/infinitude/issues/160).  Let me know if you figured it out.
