### ISSUE TITLE
Fan speed could not be set to "medium" using thermostat card

### ISSUE THREAD

**Issue by greg520820** [MizterB/homeassistant-infinitude#50]
When trying to set the fan speed by using the thermostat card and setting "Fan mode" to medium, it would return an unknown value.  I believe the thermostat requires an setting of "med" to change the speed to medium, but Home Assistant is sending "medium".  

Fixed the issue by adding the lines 646 and 647 to the climate.py file.

    def set_fan_mode(self, fan_mode):
        """Set new target fan mode.
        When set to 'auto', map to Infinity's internal value of 'off'
        """
          if fan_mode == FAN_AUTO:
              fan_mode = "off"
646    if fan_mode == FAN_MEDIUM: #added this and following line
647      fan_mode = "med"

**Comment by MizterB** [comment]
Please retry with https://github.com/MizterB/homeassistant-infinitude-beyond
