### ISSUE TITLE
Preset Temperature Range slow to update

### ISSUE THREAD

**Issue by GizmoGoody** [MizterB/homeassistant-infinitude#51]
As documented in testing [here](https://community.home-assistant.io/t/custom-component-carrier-infinity-touch-control-via-infinitude/104633/149), when I set a preset in HA, the preset name updates quickly, but the temperature values can take over a minute to indicate that preset's temperate range.

**Comment by MizterB** [comment]
This is due to the way Infinitude communicates with the thermostat.  In the my experience the settings fully sync in less than 15 seconds.  The new integration, https://github.com/MizterB/homeassistant-infinitude-beyond, will pick up these changes as soon as Infinitude makes them available.
