### ISSUE TITLE
Proper temperature unit 

### ISSUE THREAD

**Issue by sytchi** [MizterB/homeassistant-infinitude#6]
I live in Europe, and normally use Celsius over Fahrenheit. At the moment the unit is hard-coded. It would be nice if component picked it up from the API

**Comment by ccalica** [comment]
Can you describe your issue?  What units does infinitude provide?  I'd like to look into this issue but don't want to convert to metric.  Thanks.

**Comment by MizterB** [comment]
I just pushed a commit that should address this, but haven't bumped the version number yet.  Could you pull the latest and confirm that it works as expected for you?
