### ISSUE TITLE
Breaking Change in HA-Core v2023.5 & later

### ISSUE THREAD

**Issue by Darkknight33** [MizterB/homeassistant-infinitude#60]
Some change was made specifically in HA Core 2023.5.0.dev20230401 that prevents the HVAC card from reading about half of the info this integration should be providing. The breaking change is still present in as recent 2023.11.3. 

Screenshot below:

![image](https://github.com/MizterB/homeassistant-infinitude/assets/571187/f1b3f2da-91da-4e1d-915b-93f2b1401483)

**Comment by MizterB** [comment]
Please upgrade to https://github.com/MizterB/homeassistant-infinitude-beyond, which is compatible with the latest HA standards
