### ISSUE TITLE
Presence sensor data shouldn't be mandatory 

### ISSUE THREAD

**Issue by sytchi** [MizterB/homeassistant-infinitude#8]
My version of the thermostat does not support the presence detection feature. Thus Infinitude API do not return an attribute for that.

Unfortunately this leads to the component crashing during the HA load fase (and not being loaded as the result)

**Comment by bdf0506** [comment]
Comment out lines 134 and 207 of the climate.py file. Those should be the only places where it is asking about occupancy. Does that change anything?

**Comment by sytchi** [comment]
I did just hard code the 'occupied' state. It works  for now. My thermostat also lacks some other values. It would be nice if the component was smart and reported just the values that are really in the message from infinitude.

**Comment by MizterB** [comment]
This was addressed in the latest release
